/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mazaiting_ffmpegcmdtest_FFmpegCmd */

#ifndef _Included_com_mazaiting_ffmpegcmdtest_FFmpegCmd
#define _Included_com_mazaiting_ffmpegcmdtest_FFmpegCmd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mazaiting_ffmpegcmdtest_FFmpegCmd
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mazaiting_ffmpegcmdtest_FFmpegCmd_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
